
const themes = {
  tropical: [
    "./images/tropical/waves.png",
    { icon: "/images/tropical/bird-of-paradise.png", alt: "Bird of Paradise" },
    { icon: "/images/tropical/butterfly.png", alt: "butterfly" },
    { icon: "/images/tropical/coconut-drink.png", alt: "coconut drink" },
    { icon: "/images/tropical/crab.png", alt: "crab" },
    { icon: "/images/tropical/dragon-fruit.png", alt: "dragon fruit" },
    { icon: "/images/tropical/flamingo.png", alt: "flamingo" },
    { icon: "/images/tropical/flower-necklace.png", alt: "flower necklace" },
    { icon: "/images/tropical/island.png", alt: "island" },
    { icon: "/images/tropical/jellyfish.png", alt: "jellyfish" },
    { icon: "/images/tropical/lime.png", alt: "lime" },
    { icon: "/images/tropical/papaya.png", alt: "papaya" },
    { icon: "/images/tropical/parrot.png", alt: "parrot" },
    { icon: "/images/tropical/pineapple.png", alt: "pineapple" },
    { icon: "/images/tropical/sea-turtle.png", alt: "sea turtle" },
    { icon: "/images/tropical/sea.png", alt: "sea" },
    { icon: "/images/tropical/snorkel.png", alt: "snorkel" },
    { icon: "/images/tropical/starfish.png", alt: "starfish" },
    { icon: "/images/tropical/tropical-fish.png", alt: "tropical fish" },
  ],
  halloween: [
    "./images/halloween/glitter.png",
    { icon: "/images/halloween/bat.png", alt: "bat" },
    { icon: "/images/halloween/black-cat.png", alt: "black cat" },
    { icon: "/images/halloween/book.png", alt: "book" },
    { icon: "/images/halloween/candy-corn.png", alt: "candy corn" },
    {
      icon: "/images/halloween/caramelized-apple.png",
      alt: "caramelized apple",
    },
    { icon: "/images/halloween/ghost-tree.png", alt: "ghost tree" },
    { icon: "/images/halloween/ghost.png", alt: "ghost" },
    { icon: "/images/halloween/halloween-candy-1.png", alt: "gummy worms" },
    { icon: "/images/halloween/lollipop.png", alt: "lollipop" },
    { icon: "/images/halloween/monster.png", alt: "Frankenstein's monster" },
    { icon: "/images/halloween/moon.png", alt: "moon" },
    { icon: "/images/halloween/potion.png", alt: "potion" },
    { icon: "/images/halloween/pumpkin.png", alt: "jack o' lantern" },
    { icon: "/images/halloween/skull.png", alt: "skull" },
    { icon: "/images/halloween/spider.png", alt: "spider" },
    { icon: "/images/halloween/tombstone.png", alt: "tombstone" },
    { icon: "/images/halloween/werewolf.png", alt: "werewolf" },
    { icon: "/images/halloween/witch-hat.png", alt: "witch-hat" },
  ],
  space: [
    "/images/space/stars.png",
    { icon: "/images/space/alien.png", alt: "alien" },
    { icon: "/images/space/astronaut.png", alt: "astronaut" },
    { icon: "/images/space/astronomy.png", alt: "astronomy" },
    { icon: "/images/space/black-hole.png", alt: "black-hole" },
    { icon: "/images/space/earth.png", alt: "earth" },
    { icon: "/images/space/explorer.png", alt: "explorer" },
    { icon: "/images/space/galaxy.png", alt: "galaxy" },
    { icon: "/images/space/meteorites.png", alt: "meteorites" },
    { icon: "/images/space/moon.png", alt: "moon" },
    { icon: "/images/space/planet-1.png", alt: "planet 1" },
    { icon: "/images/space/planet.png", alt: "planet 2" },
    { icon: "/images/space/rocket.png", alt: "rocket" },
    { icon: "/images/space/satellite.png", alt: "satellite" },
    { icon: "/images/space/space-capsule.png", alt: "space capsule" },
    { icon: "/images/space/supernova.png", alt: "supernova" },
    { icon: "/images/space/ufo-1.png", alt: "ufo" },
    { icon: "/images/space/jupiter.png", alt: "jupiter" },
    { icon: "/images/space/ufo.png", alt: "ufo" }
  ],
  bakery: [
    "public/images/bakery/roll-out.png",
    { icon: "/images/bakery/biscuit.png", alt: "biscuit" },
    { icon: "/images/bakery/bread.png", alt: "bread" },
    { icon: "/images/bakery/cake-pop.png", alt: "cake pop" },
    { icon: "/images/bakery/carrot-cake.png", alt: "carrot cake" },
    { icon: "/images/bakery/cinnamon-roll.png", alt: "cinnamon roll" },
    { icon: "/images/bakery/cookies.png", alt: "cookies" },
    { icon: "/images/bakery/croissant.png", alt: "croissant" },
    { icon: "/images/bakery/crostata.png", alt: "pie" },
    { icon: "/images/bakery/cupcake.png", alt: "cupcake" },
    { icon: "/images/bakery/doughnut.png", alt: "doughnut" },
    { icon: "/images/bakery/fairy-bread.png", alt: "fairy bread" },
    { icon: "/images/bakery/glove.png", alt: "oven mitt" },
    { icon: "/images/bakery/macaron.png", alt: "macaron" },
    { icon: "/images/bakery/mooncake.png", alt: "moon cake" },
    { icon: "/images/bakery/panna-cotta.png", alt: "panna cotta" },
    { icon: "/images/bakery/pretzel.png", alt: "pretzel" },
    { icon: "/images/bakery/roll-cake.png", alt: "roll cake" },
    { icon: "/images/bakery/whisk.png", alt: "whisk" },
  ],
};

export default themes;
